package sk.dominika;

import java.awt.Frame;
import java.math.BigDecimal;

public class UpravitAutobusForm extends javax.swing.JDialog {

    private AutobusDao autobusDao = DaoFactory.INSTANCE.getAutobusDao();
    private Autobus autobus;

    public UpravitAutobusForm(Frame parent) {
        this(new Autobus(), parent);
    }

    public UpravitAutobusForm(Autobus autobus, Frame parent) {
        this(parent, true);
        this.autobus = autobus;

        if (autobus.getID() != -1) {
            cmbDruh.setSelectedItem(autobus.getDruh());
            cmbZnacka.setSelectedItem(autobus.getZnacka());
            txtModel.setText(autobus.getModel());
            Integer rok = autobus.getRokVyroby();
            cmbRokVyroby.setSelectedItem(rok.toString());
            Integer najazdene = autobus.getNajazdeneKm();
            txtNajazdeneKm.setText(najazdene.toString());
            txtCena.setText(autobus.getCena().toString());
        }

    }

    public UpravitAutobusForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbDruh = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbRokVyroby = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtNajazdeneKm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbZnacka = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnZrusit = new javax.swing.JButton();
        lblNazov = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Druh:");

        cmbDruh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Trolejbus", "Minibus", "Midibus", "Mestsky", "Dialkovy", "Dialkovy turisticky", "Specialne" }));
        cmbDruh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDruhActionPerformed(evt);
            }
        });

        jLabel4.setText("Rok výroby:");

        cmbRokVyroby.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969" }));
        cmbRokVyroby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRokVyrobyActionPerformed(evt);
            }
        });

        jLabel5.setText("Najazdené km:");

        jLabel2.setText("Značka:");

        cmbZnacka.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACEV", "Autosan", "Durisotti", "Ernst Auwärter", "Evobus ", "Fast Concept Car ", "Gruau", "Heuliez", "Ikarus", "Irisbus", "Jelcz", "LAZ", "MAN", "Mercedes-Benz", "Neoplan", "Novabus", "Renault Trucks", "Scania", "Setra", "Solaris", "Solbus", "SOR", "Tedom", "Temsa", "Van Hool", "VDL Bova", "VehiXel", "Volvo", " " }));
        cmbZnacka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbZnackaActionPerformed(evt);
            }
        });

        jLabel3.setText("Model:");

        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        jLabel7.setText("Cena:");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnZrusit.setText("Zrušiť");
        btnZrusit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZrusitActionPerformed(evt);
            }
        });

        lblNazov.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNazov.setText("Autobazár");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cmbDruh, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cmbRokVyroby, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblNazov)
                        .addGap(156, 156, 156))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtNajazdeneKm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbZnacka, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnZrusit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblNazov)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbZnacka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDruh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNajazdeneKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRokVyroby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnZrusit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRokVyrobyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRokVyrobyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRokVyrobyActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        autobus.setDruh(cmbDruh.getSelectedItem().toString());
        autobus.setZnacka(cmbZnacka.getSelectedItem().toString());
        autobus.setModel(txtModel.getText());
        int rok = Integer.valueOf((String) cmbRokVyroby.getSelectedItem());
        autobus.setRokVyroby(rok);
        autobus.setNajazdeneKm(Integer.parseInt(txtNajazdeneKm.getText()));
        autobus.setCena(new BigDecimal(txtCena.getText()));
        
        autobusDao.save(autobus);
        
        dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnZrusitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZrusitActionPerformed
        dispose();
    }//GEN-LAST:event_btnZrusitActionPerformed

    private void cmbDruhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDruhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDruhActionPerformed

    private void cmbZnackaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbZnackaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbZnackaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpravitMotorkuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpravitMotorkuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpravitMotorkuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpravitMotorkuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpravitMotorkuForm dialog = new UpravitMotorkuForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnZrusit;
    private javax.swing.JComboBox cmbDruh;
    private javax.swing.JComboBox cmbRokVyroby;
    private javax.swing.JComboBox cmbZnacka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblNazov;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtNajazdeneKm;
    // End of variables declaration//GEN-END:variables
}
